artem/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('home.urls', namespace='home')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

home/views.py
from django.shortcuts import render_to_response

# Create your views here.


def index(request):
    return render_to_response('home/index.html')

home/templates/home/index.html
{% extends "basepage.html" %}
{% load staticfiles %}


{% block title %} Artem Revenko {% endblock %}

{% block left_menu_entries %}
    <li><a href="http://artem.semantic-web.at">Apps</a></li>
{% endblock left_menu_entries %}

{% block right_menu_entries %}
    <li class="active"><a href="{% url 'home:index' %}">About</a></li>
{% endblock right_menu_entries %}


{% block content %}
    <img src="{% static 'home/images/me.jpg' %}" class="img-responsive img-rounded" alt="Artem Revenko" width="460" height="340" class="outstand">

    <p class="outstand">
        <a href="https://de.linkedin.com/in/artem-revenko-18318836">My LinkedIn page</a>

        <a style="margin: 8px;" href="https://scholar.google.at/citations?user=fQtKwkQAAAAJ">My Google Scholar page</a>

        <a href="http://cs.hse.ru/alumni/interview/revenko">Interview with me in russian</a>
    </p>

    <p class="outstand">I am proud to be a part of the
        <a href="https://www.semantic-web.at/">
            <img style="opacity: 0.8;" src="{% static 'home/images/swc_logo.gif' %}" alt="SWC logo" width="100" height="50">
        </a>
        team!
    </p>
{% endblock %}

templates/basepage.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
        <title>{% block title %}{% endblock title %}</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
        <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://use.fontawesome.com/f3613ef5c7.js"></script>
        <script>
            var count = 0;
            $(document).ready(function() {
                $(".loads").click( function() {
                    $("html").addClass("loading");
                });
            });
        </script>
        {% block more_js %}
        {% endblock more_js %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}" />
        {% block more_css %}
        {% endblock more_css %}
    </head>

    <body>
        <!--Navbar-->
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="">
                    <ul class="nav navbar-nav">
                        {% block left_menu_entries %}
                        {% endblock %}
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {% block right_menu_entries %}
                        {% endblock %}
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <!--End navbar-->


        <div class="container">
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                    {{ message.text }}
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>

        {% block other_content %}
        {% endblock %}

        <footer class="footer">
            {% block footer %}
                <p style="position: absolute; bottom: 0; text-align: center">2015-2017 by <a href="http://artem.revenko.space">Artem Revenko</a></p>
            {% endblock footer %}
        </footer>
    </body>
</html>